/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model;


import com.example.demo.model.tables.LibraryBooks;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index LIBRARY_ID = Indexes0.LIBRARY_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index LIBRARY_ID = Internal.createIndex("library_id", LibraryBooks.LIBRARY_BOOKS, new OrderField[] { LibraryBooks.LIBRARY_BOOKS.ID }, true);
    }
}
