/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model;


import com.example.demo.model.tables.Libraryuser;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index LIBRARYUSER_PKEY = Indexes0.LIBRARYUSER_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index LIBRARYUSER_PKEY = Internal.createIndex("LibraryUser_pkey", Libraryuser.LIBRARYUSER, new OrderField[] { Libraryuser.LIBRARYUSER.ID }, true);
    }
}
