/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model;


import com.example.demo.model.tables.Libraryuser;
import com.example.demo.model.tables.records.LibraryuserRecord;

import javax.annotation.processing.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<LibraryuserRecord, Integer> IDENTITY_LIBRARYUSER = Identities0.IDENTITY_LIBRARYUSER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LibraryuserRecord> LIBRARYUSER_PKEY = UniqueKeys0.LIBRARYUSER_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<LibraryuserRecord, Integer> IDENTITY_LIBRARYUSER = Internal.createIdentity(Libraryuser.LIBRARYUSER, Libraryuser.LIBRARYUSER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<LibraryuserRecord> LIBRARYUSER_PKEY = Internal.createUniqueKey(Libraryuser.LIBRARYUSER, "LibraryUser_pkey", Libraryuser.LIBRARYUSER.ID);
    }
}
