/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.LibraryUser_id_seq</code>
     */
    public static final Sequence<Integer> LIBRARYUSER_ID_SEQ = new SequenceImpl<Integer>("LibraryUser_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
