/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model;


import com.example.demo.model.tables.LibraryBooks;
import com.example.demo.model.tables.LibraryUser;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.library_books</code>.
     */
    public static final LibraryBooks LIBRARY_BOOKS = LibraryBooks.LIBRARY_BOOKS;

    /**
     * The table <code>public.library_user</code>.
     */
    public static final LibraryUser LIBRARY_USER = LibraryUser.LIBRARY_USER;
}
