/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Libraryuser implements Serializable {

    private static final long serialVersionUID = -2125552320;

    private Integer        id;
    private String         name;
    private String         author;
    private String         publishedBy;
    private OffsetDateTime releasedAt;
    private Integer        price;
    private OffsetDateTime createdAt;

    public Libraryuser() {}

    public Libraryuser(Libraryuser value) {
        this.id = value.id;
        this.name = value.name;
        this.author = value.author;
        this.publishedBy = value.publishedBy;
        this.releasedAt = value.releasedAt;
        this.price = value.price;
        this.createdAt = value.createdAt;
    }

    public Libraryuser(
        Integer        id,
        String         name,
        String         author,
        String         publishedBy,
        OffsetDateTime releasedAt,
        Integer        price,
        OffsetDateTime createdAt
    ) {
        this.id = id;
        this.name = name;
        this.author = author;
        this.publishedBy = publishedBy;
        this.releasedAt = releasedAt;
        this.price = price;
        this.createdAt = createdAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getPublishedBy() {
        return this.publishedBy;
    }

    public void setPublishedBy(String publishedBy) {
        this.publishedBy = publishedBy;
    }

    public OffsetDateTime getReleasedAt() {
        return this.releasedAt;
    }

    public void setReleasedAt(OffsetDateTime releasedAt) {
        this.releasedAt = releasedAt;
    }

    public Integer getPrice() {
        return this.price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Libraryuser (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(author);
        sb.append(", ").append(publishedBy);
        sb.append(", ").append(releasedAt);
        sb.append(", ").append(price);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
