/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LibraryBooks implements Serializable {

    private static final long serialVersionUID = -1973514338;

    private Integer        id;
    private String         name;
    private String         authorName;
    private Integer        libraryId;
    private OffsetDateTime releasedAt;

    public LibraryBooks() {}

    public LibraryBooks(LibraryBooks value) {
        this.id = value.id;
        this.name = value.name;
        this.authorName = value.authorName;
        this.libraryId = value.libraryId;
        this.releasedAt = value.releasedAt;
    }

    public LibraryBooks(
        Integer        id,
        String         name,
        String         authorName,
        Integer        libraryId,
        OffsetDateTime releasedAt
    ) {
        this.id = id;
        this.name = name;
        this.authorName = authorName;
        this.libraryId = libraryId;
        this.releasedAt = releasedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAuthorName() {
        return this.authorName;
    }

    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    public Integer getLibraryId() {
        return this.libraryId;
    }

    public void setLibraryId(Integer libraryId) {
        this.libraryId = libraryId;
    }

    public OffsetDateTime getReleasedAt() {
        return this.releasedAt;
    }

    public void setReleasedAt(OffsetDateTime releasedAt) {
        this.releasedAt = releasedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LibraryBooks (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(authorName);
        sb.append(", ").append(libraryId);
        sb.append(", ").append(releasedAt);

        sb.append(")");
        return sb.toString();
    }
}
