/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model.tables.records;


import com.example.demo.model.tables.LibraryUser;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.processing.Generated;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LibraryUserRecord extends TableRecordImpl<LibraryUserRecord> implements Record3<Integer, String, OffsetDateTime> {

    private static final long serialVersionUID = -467994148;

    /**
     * Setter for <code>public.library_user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.library_user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.library_user.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.library_user.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.library_user.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.library_user.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, OffsetDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, OffsetDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return LibraryUser.LIBRARY_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return LibraryUser.LIBRARY_USER.NAME;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return LibraryUser.LIBRARY_USER.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public LibraryUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LibraryUserRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public LibraryUserRecord value3(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public LibraryUserRecord values(Integer value1, String value2, OffsetDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LibraryUserRecord
     */
    public LibraryUserRecord() {
        super(LibraryUser.LIBRARY_USER);
    }

    /**
     * Create a detached, initialised LibraryUserRecord
     */
    public LibraryUserRecord(Integer id, String name, OffsetDateTime createdAt) {
        super(LibraryUser.LIBRARY_USER);

        set(0, id);
        set(1, name);
        set(2, createdAt);
    }
}
