/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model.tables.records;


import com.example.demo.model.tables.LibraryBooks;

import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LibraryBooksRecord extends UpdatableRecordImpl<LibraryBooksRecord> implements Record5<Integer, String, String, Integer, OffsetDateTime> {

    private static final long serialVersionUID = 1410156709;

    /**
     * Setter for <code>public.library_books.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.library_books.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.library_books.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.library_books.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.library_books.author_name</code>.
     */
    public void setAuthorName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.library_books.author_name</code>.
     */
    public String getAuthorName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.library_books.library_id</code>.
     */
    public void setLibraryId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.library_books.library_id</code>.
     */
    public Integer getLibraryId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.library_books.released_at</code>.
     */
    public void setReleasedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.library_books.released_at</code>.
     */
    public OffsetDateTime getReleasedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Integer, OffsetDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, Integer, OffsetDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return LibraryBooks.LIBRARY_BOOKS.ID;
    }

    @Override
    public Field<String> field2() {
        return LibraryBooks.LIBRARY_BOOKS.NAME;
    }

    @Override
    public Field<String> field3() {
        return LibraryBooks.LIBRARY_BOOKS.AUTHOR_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return LibraryBooks.LIBRARY_BOOKS.LIBRARY_ID;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return LibraryBooks.LIBRARY_BOOKS.RELEASED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getAuthorName();
    }

    @Override
    public Integer component4() {
        return getLibraryId();
    }

    @Override
    public OffsetDateTime component5() {
        return getReleasedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getAuthorName();
    }

    @Override
    public Integer value4() {
        return getLibraryId();
    }

    @Override
    public OffsetDateTime value5() {
        return getReleasedAt();
    }

    @Override
    public LibraryBooksRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LibraryBooksRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public LibraryBooksRecord value3(String value) {
        setAuthorName(value);
        return this;
    }

    @Override
    public LibraryBooksRecord value4(Integer value) {
        setLibraryId(value);
        return this;
    }

    @Override
    public LibraryBooksRecord value5(OffsetDateTime value) {
        setReleasedAt(value);
        return this;
    }

    @Override
    public LibraryBooksRecord values(Integer value1, String value2, String value3, Integer value4, OffsetDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LibraryBooksRecord
     */
    public LibraryBooksRecord() {
        super(LibraryBooks.LIBRARY_BOOKS);
    }

    /**
     * Create a detached, initialised LibraryBooksRecord
     */
    public LibraryBooksRecord(Integer id, String name, String authorName, Integer libraryId, OffsetDateTime releasedAt) {
        super(LibraryBooks.LIBRARY_BOOKS);

        set(0, id);
        set(1, name);
        set(2, authorName);
        set(3, libraryId);
        set(4, releasedAt);
    }
}
