/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model.tables.records;


import com.example.demo.model.tables.Libraryuser;

import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LibraryuserRecord extends UpdatableRecordImpl<LibraryuserRecord> implements Record7<Integer, String, String, String, OffsetDateTime, Integer, OffsetDateTime> {

    private static final long serialVersionUID = -128390489;

    /**
     * Setter for <code>public.LibraryUser.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.LibraryUser.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.LibraryUser.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.LibraryUser.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.LibraryUser.author</code>.
     */
    public void setAuthor(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.LibraryUser.author</code>.
     */
    public String getAuthor() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.LibraryUser.published by</code>.
     */
    public void setPublishedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.LibraryUser.published by</code>.
     */
    public String getPublishedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.LibraryUser.released at</code>.
     */
    public void setReleasedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.LibraryUser.released at</code>.
     */
    public OffsetDateTime getReleasedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.LibraryUser.price</code>.
     */
    public void setPrice(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.LibraryUser.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.LibraryUser.created at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.LibraryUser.created at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, OffsetDateTime, Integer, OffsetDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, OffsetDateTime, Integer, OffsetDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Libraryuser.LIBRARYUSER.ID;
    }

    @Override
    public Field<String> field2() {
        return Libraryuser.LIBRARYUSER.NAME;
    }

    @Override
    public Field<String> field3() {
        return Libraryuser.LIBRARYUSER.AUTHOR;
    }

    @Override
    public Field<String> field4() {
        return Libraryuser.LIBRARYUSER.PUBLISHED_BY;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Libraryuser.LIBRARYUSER.RELEASED_AT;
    }

    @Override
    public Field<Integer> field6() {
        return Libraryuser.LIBRARYUSER.PRICE;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return Libraryuser.LIBRARYUSER.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getAuthor();
    }

    @Override
    public String component4() {
        return getPublishedBy();
    }

    @Override
    public OffsetDateTime component5() {
        return getReleasedAt();
    }

    @Override
    public Integer component6() {
        return getPrice();
    }

    @Override
    public OffsetDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getAuthor();
    }

    @Override
    public String value4() {
        return getPublishedBy();
    }

    @Override
    public OffsetDateTime value5() {
        return getReleasedAt();
    }

    @Override
    public Integer value6() {
        return getPrice();
    }

    @Override
    public OffsetDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public LibraryuserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LibraryuserRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public LibraryuserRecord value3(String value) {
        setAuthor(value);
        return this;
    }

    @Override
    public LibraryuserRecord value4(String value) {
        setPublishedBy(value);
        return this;
    }

    @Override
    public LibraryuserRecord value5(OffsetDateTime value) {
        setReleasedAt(value);
        return this;
    }

    @Override
    public LibraryuserRecord value6(Integer value) {
        setPrice(value);
        return this;
    }

    @Override
    public LibraryuserRecord value7(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public LibraryuserRecord values(Integer value1, String value2, String value3, String value4, OffsetDateTime value5, Integer value6, OffsetDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LibraryuserRecord
     */
    public LibraryuserRecord() {
        super(Libraryuser.LIBRARYUSER);
    }

    /**
     * Create a detached, initialised LibraryuserRecord
     */
    public LibraryuserRecord(Integer id, String name, String author, String publishedBy, OffsetDateTime releasedAt, Integer price, OffsetDateTime createdAt) {
        super(Libraryuser.LIBRARYUSER);

        set(0, id);
        set(1, name);
        set(2, author);
        set(3, publishedBy);
        set(4, releasedAt);
        set(5, price);
        set(6, createdAt);
    }
}
